/* sync-seccore.mjs — regenerate app/crosslab/secsim-core.mjs from the inline
   engine inside physics_simulator.html so the browser console page and every
   node tool run the exact same Sim as the research tool.

   Usage:
     node sync-seccore.mjs            write secsim-core.mjs (re-generated)
     node sync-seccore.mjs --check    exit nonzero if it is out of date
     node sync-seccore.mjs --dry      print the generated module to stdout
*/

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.dirname(new URL(import.meta.url).pathname);
const HTML = path.join(ROOT, '..', 'app', 'crosslab', 'physics_simulator.html');
const OUT = path.join(ROOT, '..', 'app', 'crosslab', 'secsim-core.mjs');
const SRC = fs.readFileSync(HTML, 'utf8');

function braceMatch(open){
  let depth = 0;
  for (let i = open; i < SRC.length; i++){
    if (SRC[i] === '{') depth++;
    else if (SRC[i] === '}'){ depth--; if (depth === 0) return i; }
  }
  throw new Error('unbalanced brace from ' + open);
}

// CFG object literal { … }
const cfgMarker = 'const CFG = {';
const cfgOpen = SRC.indexOf(cfgMarker) + cfgMarker.length - 1;
if (cfgOpen < cfgMarker.length) throw new Error('CFG marker not found');
const CFG_LIT = SRC.slice(cfgOpen, braceMatch(cfgOpen) + 1);

// SpatialMap + PAC + AUTO_STRATS + Sim, up to the RENDERER banner
const simStart = SRC.indexOf('class SpatialMap');
const simEnd = SRC.indexOf('// ─── RENDERER');
if (simStart < 0 || simEnd < 0) throw new Error('sim region not found');
const SIM_CODE = SRC.slice(simStart, simEnd);

const MODULE = `/**
 * secsim-core.mjs — AUTO-GENERATED by node-tests/sync-seccore.mjs.
 * Do not edit by hand: every change lives in
 *   app/crosslab/physics_simulator.html
 * Re-build with:  node node-tests/sync-seccore.mjs
 * The defense console page and the node tools import this module so they share
 * the exact same CFG, SpatialMap and Sim as the research tool.
 */
export const CFG = ${CFG_LIT};

${SIM_CODE}

export { SpatialMap, Sim };
`;

const mode = process.argv[2] || 'write';
const wantSmoke = process.argv.includes('--smoke');
if (mode === '--dry'){
  process.stdout.write(MODULE);
} else if (mode === '--check'){
  let cur = '';
  try { cur = fs.readFileSync(OUT, 'utf8'); } catch (e) { /* absent */ }
  if (cur !== MODULE){
    console.error('SECCORE-OUT-OF-DATE — run node-tests/sync-seccore.mjs');
    process.exit(1);
  }
  console.log('SECCORE-OK: secsim-core.mjs matches physics_simulator.html (' + MODULE.length + ' bytes)');
  if (wantSmoke) await smoke();
  else process.exit(0);
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, MODULE);
  console.log('SECCORE-WRITTEN: ' + OUT + ' (' + MODULE.length + ' bytes)');
  if (wantSmoke) await smoke();
}

async function smoke(){
  // Boot the real engine once to prove the generated module is runnable and
  // that quarantine/deploy/attacker-source primitives actually work end-to-end.
  const { CFG, Sim } = await import('../app/crosslab/secsim-core.mjs');
  CFG.security = true; CFG.threatLevel = 0.6; CFG.firewall = 0.7;
  const sim = new Sim();
  for (let i = 0; i < 150; i++) sim.update(8);
  const atk = sim.agents.find(a => a.role === 'attacker');
  const reported = atk ? sim.attackerSource(atk) : null;
  const n = sim.nearestNode(0, 0, 0);
  const q = sim.quarantineNode(n);
  const d = sim.deployDefender(0.5, 0.5, -0.5);
  const srcOK = !!(reported && reported.hash && reported.proto && reported.ip && reported.target >= 0);
  const defOK = sim.countRole('defender') >= 1 && d === true;
  const isoOK = q === true && sim.quarantined.size === 1 && sim.releaseNode(n) === true && sim.quarantined.size === 0;
  if (!srcOK || !defOK || !isoOK){
    console.error('SECCORE-SMOKE-FAIL', { srcOK, defOK, isoOK, reported });
    process.exit(1);
  }
  console.log('SECCORE-SMOKE-OK: source telemetry ✓ quarantine/release ✓ deploy ✓ defenders=' + sim.countRole('defender') + ' intrusions=' + sim.intrusions + ' blocked=' + sim.blocked);
}