/**
 * secsim-core.mjs — AUTO-GENERATED by node-tests/sync-seccore.mjs.
 * Do not edit by hand: every change lives in
 *   app/crosslab/physics_simulator.html
 * Re-build with:  node node-tests/sync-seccore.mjs
 * The defense console page and the node tools import this module so they share
 * the exact same CFG, SpatialMap and Sim as the research tool.
 */
export const CFG = {
  numAgents: 200, numNodes: 180, agentSpeed: 0.15,
  evaporation: 0.985, diffusion: 0.1,
  sensorAngle: 0.628, rotationAngle: 0.524, sensorDistance: 2.0,
  alignStrength: 0.008, repulsionStrength: 0.04,
  damping: 0.94, maxConnections: 4, connectionThreshold: 1.2,
  trailRes: 32, trailIntensity: 0.12,
  gravity: 0.18, quantum: 0.15, entangle: 0.3,
  tunnel: 0.1, curvature: 0.25, energyShells: 4,
  darkEnergy: 0.05, inflation: 0.0, fineStructure: 1.0,
  strongForce: 0.06, weakForce: 0.05, higgsField: 0.3,
  decoherence: 0.02, vacuumEnergy: 0.01, planckScale: 0.0,
  // harmony hooks: gentle orbital revolution + short-range separation keep an
  // orderly multi-cluster ensemble instead of one collapsing giant blob
  orbital: 0.15, separation: 0.12,
  // mesh shells: pin nodes to concentric shell walls so the ensemble reads as a
  // stable world/cluster of devices instead of collapsing to a single point.
  // The spring backs off when gravity is high so web-forming presets survive.
  meshShell: true,
  // security-system demo knobs
  security: false, threatLevel: 0.2, firewall: 0.7,
  defenderCount: 6, attackerBatch: 40, attackTrails: true,
  // moving-target auto-defense: rotates defense strategies that steer defenders
  // along wholly unique per-agent paths through the data lattice
  autoDefense: false, autoDefRotate: 60,
  // camera-focus tracking
  trackFocus: false, trackCount: 5,
  runSpeed: 0.25,   // physics steps advanced per animation frame while running
  entropyVis: false, waveFunc: false, gravLens: false,
  showGrid: true, showAgents: true, showConnections: true,
  autoRotate: false, trailHeatmap: false,
  nodeColor: '#00ffff', agentColor: '#00ffff', connectColor: '#00ffff', bgColor: '#000000',
  colorOffset: 0.3, colorIntensity: 0.7,
  renderStyle: 'points', preset: 'custom',
  nodeOpacity: 0.9, glowSize: 1.0,
};

class SpatialMap {
  constructor(cellSize = 2) {
    this.cellSize = cellSize;
    this.map = new Map();
  }
  clear() { this.map.clear(); }
  key(x, y, z) { return `${Math.floor(x/this.cellSize)},${Math.floor(y/this.cellSize)},${Math.floor(z/this.cellSize)}`; }
  insert(idx, x, y, z) {
    const k = this.key(x, y, z);
    if (!this.map.has(k)) this.map.set(k, []);
    this.map.get(k).push(idx);
  }
  query(x, y, z, radius) {
    const result = [];
    const r = Math.ceil(radius / this.cellSize);
    const cx = Math.floor(x / this.cellSize), cy = Math.floor(y / this.cellSize), cz = Math.floor(z / this.cellSize);
    for (let dx = -r; dx <= r; dx++) for (let dy = -r; dy <= r; dy++) for (let dz = -r; dz <= r; dz++) {
      const k = `${cx+dx},${cy+dy},${cz+dz}`;
      if (this.map.has(k)) result.push(...this.map.get(k));
    }
    return result;
  }
}

// Auto-defense unique-path lattice: defenders sweep an 8³ volumetric grid of
// the field data, each on its own low-discrepancy trajectory (no two share a
// route). Kept above `class Sim` (and after SpatialMap) so the headless harness
// slice — from `class SpatialMap` to the RENDERER banner — captures them too.
const PAC = 8;
const AUTO_STRATS = ['sweep', 'perimeter', 'rash', 'pursuit'];

// ─── SIMULATION ─────────────────────────────────────────────────────────
class Sim {
  constructor() {
    this.agents = [];
    this.nodePos = new Float32Array(0);
    this.nodeVel = new Float32Array(0);
    this.nodeWeight = new Float32Array(0);
    this.nodeBias = new Float32Array(0);
    this.nodeAct = new Float32Array(0);
    this.nodeMass = new Float32Array(0);
    this.nodeCharge = new Float32Array(0);
    this.nodeSpin = new Float32Array(0);
    this.nodeWaveReal = new Float32Array(0);
    this.nodeWaveImag = new Float32Array(0);
    this.nodeShell = new Float32Array(0);
    this.nodeHomeR = new Float32Array(0);
    this.nodeEntangle = [];
    this.nodeData = [];
    this.connections = [];
    this.spatial = new SpatialMap(2.5);
    this.entropy = 0;
    this.totalEnergy = 0;
    this.history = [];
    this.blocked = 0;
    this.intrusions = 0;
    this.peakStress = 0;
    this.events = [];
    this.pulses = [];
    this.compromised = new Set();
    this.secTick = 0;
    this.step = 0;
    this.auto = {
      on: false, prepped: false, index: 0, strategy: 'pursuit', rotation: 0,
      seed: 1234567, ticks: 0, coverCount: 0, intercepts: 0,
      coverSeen: new Uint8Array(PAC * PAC * PAC), stratTicks: {},
    };
    // Defense console working state: quarantined nodes are electronically
    // isolated from the ensemble, deployed defenders are manual reinforcements,
    // and attackers carry sanitized source telemetry for the inspection UI.
    this.quarantined = new Set();
    this.deployedDefenders = 0;
    this.attackerSeq = 0;
    this.defenseLedger = [];
    this.resize(CFG.numNodes, CFG.numAgents);
  }

  simHash(str){
    let h = 2166136261 >>> 0;
    for (let i = 0; i < str.length; i++){ h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); }
    return (h >>> 0).toString(16).padStart(8, '0');
  }
  attackerSource(a){
    if (!a || a.role !== 'attacker' || !a.src) return null;
    const n = this.nearestNode(a.px, a.py, a.pz);
    const s = a.src;
    return {
      id: s.id, hash: s.hash, ip: s.ip, port: s.port, proto: s.proto,
      hops: s.hops, ttl: s.ttl, vector: s.vector, risk: s.risk,
      firstSeen: s.since, live: this.step - s.since,
      target: n >= 0 ? n : -1, targetLabel: n >= 0 ? this.nodeData[n].label : '—',
      pos: [a.px, a.py, a.pz], speed: +a.spd.toFixed(3), quarantine: this.quarantined.has(n),
    };
  }
  // ── defense console primitives ─────────────────────────────────────────
  quarantineNode(i){
    if (i < 0 || i >= CFG.numNodes || this.quarantined.has(i)) return false;
    this.quarantined.add(i);
    this.nodeWeight[i] = Math.max(0.05, this.nodeWeight[i] - 0.15);
    this.defenseLedger.push({ step: this.step, kind: 'quarantine', node: i, label: this.nodeData[i].label });
    this.logSec('quarantine', 'node ' + this.nodeData[i].label + ' isolated from the ensemble');
    return true;
  }
  releaseNode(i){
    if (!this.quarantined.has(i)) return false;
    this.quarantined.delete(i);
    this.defenseLedger.push({ step: this.step, kind: 'release', node: i, label: this.nodeData[i].label });
    this.logSec('release', 'node ' + this.nodeData[i].label + ' re-linked');
    return true;
  }
  deployDefender(x, y, z){
    if (this.agents.length >= 1024) return false;
    this.agents.push({
      px: x, py: y, pz: z, dx: Math.random() - 0.5, dy: Math.random() - 0.5, dz: Math.random() - 0.5,
      spd: 0.35, phase: Math.random() * Math.PI * 2, tunnelCD: 0, role: 'defender', removed: false, manual: true,
    });
    this.deployedDefenders++;
    this.defenseLedger.push({ step: this.step, kind: 'deploy', at: [x, y, z] });
    this.logSec('deploy', 'manual defender air-dropped at ' + Math.round(x*10)/10 + ',' + Math.round(y*10)/10);
    return true;
  }

  resize(numNodes, numAgents) {
    const R = CFG.trailRes;
    this.trail = new Float32Array(R * R * R);
    this.trail2 = new Float32Array(R * R * R);
    this.curvatureMap = new Float32Array(R * R * R);
    this.stress = new Float32Array(numNodes);
    this.nodePos = new Float32Array(numNodes * 3);
    this.nodeVel = new Float32Array(numNodes * 3);
    this.nodeWeight = new Float32Array(numNodes);
    this.nodeBias = new Float32Array(numNodes);
    this.nodeAct = new Float32Array(numNodes);
    this.nodeMass = new Float32Array(numNodes);
    this.nodeCharge = new Float32Array(numNodes);
    this.nodeSpin = new Float32Array(numNodes);
    this.nodeWaveReal = new Float32Array(numNodes);
    this.nodeWaveImag = new Float32Array(numNodes);
    this.nodeShell = new Float32Array(numNodes);
    this.nodeHomeR = new Float32Array(numNodes);
    this.nodeEntangle = new Array(numNodes);
    this.nodeData = [];
    this.connections = new Array(numNodes);
    for (let i = 0; i < numNodes; i++) { this.connections[i] = []; this.nodeEntangle[i] = []; }
    const n = numNodes;
    for (let i = 0; i < n; i++) {
      let px, py, pz, homeR;
      const useShells = CFG.meshShell && n > 24;
      if (useShells) {
        // Concentric shell walls — a layered "world / cluster of devices" that
        // reads as a stable mesh wall instead of a collapsing point.
        const SHELLS = [3.2, 5.4];
        const sk = i % SHELLS.length;
        const R = SHELLS[sk];
        const local = Math.floor(i / SHELLS.length);
        const count = Math.max(2, Math.ceil(n / SHELLS.length));
        const g = (Math.PI * (3 - Math.sqrt(5))) * (local + 0.5);
        const y = 1 - ((local % count) / count) * 2;
        const r = Math.sqrt(Math.max(0, 1 - y * y));
        px = R * Math.cos(g) * r;
        py = R * y;
        pz = R * Math.sin(g) * r;
        homeR = R;
      } else {
        const theta = Math.random() * Math.PI * 2, phi = Math.acos(2 * Math.random() - 1);
        const r = Math.pow(Math.random(), 1.5) * 6;
        px = r * Math.sin(phi) * Math.cos(theta);
        py = r * Math.sin(phi) * Math.sin(theta);
        pz = r * Math.cos(phi);
        homeR = r;
      }
      this.nodePos[i*3] = px;
      this.nodePos[i*3+1] = py;
      this.nodePos[i*3+2] = pz;
      this.nodeHomeR[i] = homeR;
      this.nodeWeight[i] = Math.random();
      this.nodeBias[i] = Math.random() * 0.5;
      this.nodeMass[i] = 0.5 + Math.random();
      this.nodeCharge[i] = (Math.random() - 0.5) * 2;
      this.nodeSpin[i] = (Math.random() > 0.5 ? 1 : -1) * (0.5 + Math.random() * 0.5);
      this.nodeWaveReal[i] = Math.random() * 0.5;
      this.nodeWaveImag[i] = Math.random() * 0.5;
      this.nodeShell[i] = Math.floor(Math.random() * (CFG.energyShells + 1));
      this.nodeData.push({ label: `n${i}`, data: '' });
    }
    for (let i = 0; i < n; i++) {
      if (this.nodeEntangle[i].length === 0 && Math.random() < 0.15) {
        let j = Math.floor(Math.random() * n);
        if (j !== i && this.nodeEntangle[j].length === 0) { this.nodeEntangle[i].push(j); this.nodeEntangle[j].push(i); }
      }
    }
    this.agents = [];
    for (let i = 0; i < numAgents; i++) {
      this.agents.push({
        px: (Math.random() - 0.5) * 10, py: (Math.random() - 0.5) * 10, pz: (Math.random() - 0.5) * 10,
        dx: Math.random() - 0.5, dy: Math.random() - 0.5, dz: Math.random() - 0.5,
        spd: 0.15 + Math.random() * 0.1, phase: Math.random() * Math.PI * 2, tunnelCD: 0,
        role: 'legit', removed: false,
      });
      const a = this.agents[i]; const len = Math.sqrt(a.dx*a.dx + a.dy*a.dy + a.dz*a.dz) || 1;
      a.dx /= len; a.dy /= len; a.dz /= len;
    }
  }

  logSec(type, msg){
    this.events.push({ step: this.step, type, msg });
    if (this.events.length > 40) this.events.shift();
  }
  countRole(role){ let c = 0; for (const a of this.agents) if (a.role === role) c++; return c; }
  nearestNode(px, py, pz){
    let best = -1, bd = Infinity;
    for (let i = 0; i < CFG.numNodes; i++){
      const dx = this.nodePos[i*3] - px, dy = this.nodePos[i*3+1] - py, dz = this.nodePos[i*3+2] - pz;
      const d2 = dx*dx + dy*dy + dz*dz;
      if (d2 < bd){ bd = d2; best = i; }
    }
    return best;
  }
  applyShellLayout(){
    const n = CFG.numNodes;
    if (CFG.meshShell && n > 24){
      const SHELLS = [3.2, 5.4];
      for (let i = 0; i < n; i++){
        const sk = i % SHELLS.length;
        const R = SHELLS[sk];
        const local = Math.floor(i / SHELLS.length);
        const count = Math.max(2, Math.ceil(n / SHELLS.length));
        const g = (Math.PI * (3 - Math.sqrt(5))) * (local + 0.5);
        const y = 1 - ((local % count) / count) * 2;
        const r = Math.sqrt(Math.max(0, 1 - y * y));
        this.nodePos[i*3] = R * Math.cos(g) * r;
        this.nodePos[i*3+1] = R * y;
        this.nodePos[i*3+2] = R * Math.sin(g) * r;
        this.nodeHomeR[i] = R;
        this.nodeVel[i*3] = 0; this.nodeVel[i*3+1] = 0; this.nodeVel[i*3+2] = 0;
      }
    }
  }
  spawnAttackers(n){
    for (let i = 0; i < n && this.agents.length < 1024; i++){
      const proto = i % 3 === 0 ? 'syn-flood' : i % 3 === 1 ? 'dns-amp' : 'tls-reneg';
      const hops = 2 + Math.floor(Math.random() * 9);
      const ip = '192.0.2.' + (1 + Math.floor(Math.random() * 253));
      const sig = ip + ':' + (80 + Math.floor(Math.random() * 65500)) + ':' + proto + ':' + this.attackerSeq;
      this.attackerSeq++;
      this.agents.push({
        px: (Math.random() - 0.5) * 14, py: (Math.random() - 0.5) * 14, pz: (Math.random() - 0.5) * 14,
        dx: Math.random() - 0.5, dy: Math.random() - 0.5, dz: Math.random() - 0.5,
        spd: 0.4, phase: Math.random() * Math.PI * 2, tunnelCD: 0, role: 'attacker', removed: false,
        src: {
          id: 'ATK-' + String(this.attackerSeq).padStart(3, '0'),
          ip, port: 80 + Math.floor(Math.random() * 65500),
          proto, hops, ttl: 64 - hops,
          risk: +(0.4 + Math.random() * 0.6).toFixed(2),
          since: this.step, hash: this.simHash(sig),
        },
      });
    }
  }
  spawnDefenders(n){
    for (let i = 0; i < n; i++){
      this.agents.push({
        px: (Math.random() - 0.5) * 2, py: (Math.random() - 0.5) * 2, pz: (Math.random() - 0.5) * 2,
        dx: Math.random() - 0.5, dy: Math.random() - 0.5, dz: Math.random() - 0.5,
        spd: 0.35, phase: Math.random() * Math.PI * 2, tunnelCD: 0, role: 'defender', removed: false,
      });
    }
  }
  launchBurst(n){
    this.spawnAttackers(n);
    this.logSec('burst', 'DDoS burst inbound — ' + n + ' agents');
  }
  // ── moving-target auto-defense ──────────────────────────────────────────
  // The controller re-arms its counters and immediately rotates to a strategy;
  // thereafter it rotates on every autoDefRotate ticks. Sweep defenders move on
  // unique per-agent paths through the volumetric data (see adCell/adPatrolDir).
  autoPrepH(){
    const ad = this.auto;
    ad.on = true; ad.prepped = true; ad.index = 0; ad.rotation = 0;
    ad.ticks = 0; ad.coverCount = 0; ad.intercepts = 0;
    ad.strategy = 'pursuit'; ad.stratTicks = {};
    ad.coverSeen.fill(0);
    ad.seed = (((Math.floor(Math.sin(CFG.threatLevel * 11.7 + this.step) * 100000)) % 2147483647) + 2147483647) % 2147483647 || 1234567;
    this.autoRotate();
  }
  autoRotate(){
    const ad = this.auto;
    ad.rotation++;
    // Every rotation re-seeds the path lattice deterministically (linear mix of
    // the prior seed + step + rotation) — each strategy pass sweeps a fresh route
    // field, so defenders never retrace a rotation and it stays reproducible
    // (no basic Math.random anywhere in the path planner).
    ad.seed = ((ad.seed * 1103515245 + this.step + ad.rotation * 7919) & 0x7fffffff) || 1234567;
    ad.index = (ad.index + 1) % AUTO_STRATS.length;
    ad.strategy = AUTO_STRATS[ad.index];
    ad.stratTicks[ad.strategy] = 0;
    // defender phase offsets derive from the rotation seed too — deterministic per defender
    let di = 0;
    for (const a of this.agents) if (a.role === 'defender'){ a.pathStep = this._hs(ad.seed + di * 13, 5) % 40; di++; }
    this.logSec('auto', 'moving-target rotation ' + ad.rotation + ' → ' + ad.strategy + ' · path seed ' + ad.seed);
  }
  manualRotate(){ if (!this.auto.prepped) this.autoPrepH(); else this.autoRotate(); }
  _hs(v, salt){
    v = (v + salt * 0x9e3779b9) >>> 0;
    v = (v ^ (v >>> 16)) * 0x7feb352d >>> 0;
    v = (v ^ (v >>> 15)) * 0x846ca68b >>> 0;
    return (v ^ (v >>> 16)) >>> 0;
  }
  adCell(di, step, seed){
    const R = PAC;
    const x = this._hs(di * 7919 + step * 1013 + seed, 1) % R;
    const y = this._hs(di * 104729 + step * 1777 + seed, 2) % R;
    const z = this._hs(di * 16127 + step * 1423 + seed, 3) % R;
    return (x * R + y) * R + z;
  }
  adPatrolDir(d, did){
    const R = PAC, RANGE = 8;
    const sp = d.pathStep || 0;
    d.pathStep = sp + 1;
    const cell = this.adCell(did, sp, this.auto.seed);
    const wx = ((Math.floor(cell / (R * R)) % R) + 0.5) / R * 2 * RANGE - RANGE;
    const wy = ((Math.floor(cell / R) % R) + 0.5) / R * 2 * RANGE - RANGE;
    const wz = ((cell % R) + 0.5) / R * 2 * RANGE - RANGE;
    if (!this.auto.coverSeen[cell]){ this.auto.coverSeen[cell] = 1; this.auto.coverCount++; }
    const dx = wx - d.px, dy = wy - d.py, dz = wz - d.pz;
    const dist = Math.sqrt(dx*dx + dy*dy + dz*dz) || 1;
    if (dist < 0.55) d.pathStep = sp + 40;
    return { x: dx / dist, y: dy / dist, z: dz / dist };
  }
  // One pass of the security-system simulation: defenders hunt and neutralize
  // attackers, attackers seek nodes and stress them, firewall heals degraded
  // nodes back to a harmonious baseline.
  secStep(){
    if (!CFG.security){ this.pulses.length = 0; return; }
    this.agents = this.agents.filter(a => !(a.role === 'attacker' && a.removed));

    // moving-target controller: advance the rotation timer and keep the active
    // strategy live while the auto-defense switch is on
    this.auto.on = CFG.autoDefense && CFG.security;
    if (this.auto.on){
      if (!this.auto.prepped) this.autoPrepH();
      this.auto.ticks++;
      if (this.auto.ticks >= Math.max(20, Math.round(CFG.autoDefRotate))){ this.autoRotate(); this.auto.ticks = 0; }
      this.auto.stratTicks[this.auto.strategy] = (this.auto.stratTicks[this.auto.strategy] || 0) + 1;
    }

    // defenders pursue attackers — or run the active moving-target strategy.
    // Each strategy changes target selection, kill rate and dash speed; 'sweep'
    // instead patrols on wholly unique per-defender paths through the volumetric
    // lattice and intercepts only at close range.
    let di = 0;
    for (const d of this.agents){
      if (d.role !== 'defender') continue;
      const did = di++;
      const strat = this.auto.on ? this.auto.strategy : 'pursuit';
      let best = null, bd = Infinity, kill = CFG.firewall * 0.35, spd = 0.35;
      // Defenders guard quarantined nodes in priority: any attacker inside the
      // quarantine ring around an isolated node is the first target.
      let guard = null, guardD = Infinity;
      for (const q of this.quarantined){
        const nx = this.nodePos[q*3], ny = this.nodePos[q*3+1], nz = this.nodePos[q*3+2];
        const ddx = d.px - nx, ddy = d.py - ny, ddz = d.pz - nz;
        const dg = ddx*ddx + ddy*ddy + ddz*ddz;
        if (dg < guardD){ guardD = dg; guard = q; }
      }
      if (guard != null) for (const a of this.agents){
        if (a.role !== 'attacker') continue;
        const gx = this.nodePos[guard*3] - a.px, gy = this.nodePos[guard*3+1] - a.py, gz = this.nodePos[guard*3+2] - a.pz;
        const gr = gx*gx + gy*gy + gz*gz;
        if (gr < 16 && gr < bd){ bd = gr; best = a; }
      }
      for (const a of this.agents){
        if (a.role !== 'attacker') continue;
        const dx = a.px - d.px, dy = a.py - d.py, dz = a.pz - d.pz;
        const d2 = dx*dx + dy*dy + dz*dz;
        if (strat === 'sweep'){
          if (d2 < 6.25 && d2 < bd){ bd = d2; best = a; }
          kill = CFG.firewall * 0.42;
        } else if (strat === 'perimeter'){
          const aCore = a.px*a.px + a.py*a.py + a.pz*a.pz;
          if (d2 < 64 && aCore < 36 && d2 < bd){ bd = d2; best = a; }
          kill = CFG.firewall * 0.30;
        } else if (strat === 'rash'){
          if (d2 < 120 && d2 < bd){ bd = d2; best = a; }
          spd = 0.48; kill = CFG.firewall * 0.60;
        } else if (d2 < 100 && d2 < bd){ bd = d2; best = a; }
      }
      let tx = 0, ty = 0, tz = 0;
      if (best){
        const nbx = best.px - d.px, nby = best.py - d.py, nbz = best.pz - d.pz;
        const nd = Math.sqrt(nbx*nbx + nby*nby + nbz*nbz) || 1;
        tx = nbx/nd; ty = nby/nd; tz = nbz/nd;
      } else if (strat === 'sweep'){
        const p = this.adPatrolDir(d, did);
        tx = p.x; ty = p.y; tz = p.z;
      } else {
        continue;
      }
      d.dx = -tx; d.dy = -ty; d.dz = -tz; d.spd = spd;
      if (best){
        const dx = best.px - d.px, dy = best.py - d.py, dz = best.pz - d.pz;
        const dist = Math.sqrt(dx*dx + dy*dy + dz*dz) || 1;
        if (dist < 1.5 && Math.random() < kill){
          best.removed = true;
          this.blocked++;
          if (strat === 'sweep' || strat === 'perimeter') this.auto.intercepts++;
          this.logSec('blocked', 'firewall neutralized attacker at ' + Math.round(best.px*10)/10 + ',' + Math.round(best.py*10)/10);
        }
      }
    }
    this.agents = this.agents.filter(a => !(a.role === 'attacker' && a.removed));

    // attackers hunt the node that hurts the ensemble most
    for (const a of this.agents){
      if (a.role !== 'attacker') continue;
      const n = this.nearestNode(a.px, a.py, a.pz);
      if (n < 0) continue;
      const isolated = this.quarantined.has(n);
      const nx = this.nodePos[n*3], ny = this.nodePos[n*3+1], nz = this.nodePos[n*3+2];
      const dx = nx - a.px, dy = ny - a.py, dz = nz - a.pz;
      const dist = Math.sqrt(dx*dx + dy*dy + dz*dz) || 1;
      // Quarantined nodes are electrically isolated: attacks punch no farther than
      // the quarantine ring around them and cannot compromise the node itself.
      a.dx = dx / dist; a.dy = dy / dist; a.dz = dz / dist; a.spd = 0.4;
      const ring = isolated ? 1.9 : 0.9;
      if (dist < ring){
        const ef = 0.03 * (CFG.threatLevel + 0.2) * (1.5 - CFG.firewall);
        if (isolated){
          this.blocked++;
          a.removed = true;
          this.auto.intercepts++;
          this.logSec('deferred', 'branch routed ' + a.src.id + ' away from quarantined ' + this.nodeData[n].label);
          continue;
        }
        this.stress[n] += ef;
        this.peakStress = Math.max(this.peakStress, this.stress[n]);
        this.nodeWeight[n] = Math.max(0.05, this.nodeWeight[n] - ef);
        if (this.nodeWeight[n] < 0.3 && !this.compromised.has(n)){
          this.compromised.add(n);
          this.intrusions++;
          this.logSec('intrusion', 'node ' + this.nodeData[n].label + ' compromised');
        }
        if (CFG.attackTrails && this.pulses.length < 60)
          this.pulses.push([a.px, a.py, a.pz, nx, ny, nz]);
      }
    }
    if (this.pulses.length > 60) this.pulses = this.pulses.slice(-60);

    // firewall healing + stress decay keeps the system harmonious
    for (let i = 0; i < CFG.numNodes; i++) this.stress[i] *= 0.995;
    const toUnset = [];
    for (const i of this.compromised){
      if (CFG.firewall > 0.1 && Math.random() < CFG.firewall * 0.05)
        this.nodeWeight[i] = Math.min(1, this.nodeWeight[i] + 0.03);
      if (this.nodeWeight[i] > 0.55){ toUnset.push(i); this.logSec('secured', 'node ' + this.nodeData[i].label + ' restored'); }
    }
    for (const i of toUnset) this.compromised.delete(i);

    // population balance: refresh defenders, hold ambient attackers, DDoS waves
    this.secTick++;
    if (this.secTick % 20 === 0){
      const wantA = Math.round(CFG.threatLevel * 30);
      const nowA = this.countRole('attacker');
      if (nowA < wantA) this.spawnAttackers(wantA - nowA);
      if (nowA > wantA + 10) {
        let excess = nowA - wantA;
        for (const a of this.agents) if (a.role === 'attacker' && excess-- > 0) a.removed = true;
        this.agents = this.agents.filter(a => !(a.role === 'attacker' && a.removed));
      }
      const wantD = CFG.defenderCount;
      const nowD = this.countRole('defender');
      if (nowD < wantD) this.spawnDefenders(wantD - nowD);
    }
    if (this.secTick % 100 === 0 && CFG.threatLevel > 0) this.launchBurst(CFG.attackerBatch);
  }

  idx(x, y, z) {
    const R = CFG.trailRes;
    const ix = ((Math.floor(((x + 100) % 1) * R)) % R + R) % R;
    const iy = ((Math.floor(((y + 100) % 1) * R)) % R + R) % R;
    const iz = ((Math.floor(((z + 100) % 1) * R)) % R + R) % R;
    return (ix * R + iy) * R + iz;
  }
  getTrail(x, y, z) { return this.trail[this.idx(x, y, z)]; }
  getCurvature(x, y, z) { return this.curvatureMap[this.idx(x, y, z)]; }
  deposit(x, y, z, amt) { this.trail[this.idx(x, y, z)] = Math.min(1, this.trail[this.idx(x, y, z)] + amt); }

  sense(px, py, pz, dx, dy, dz, angle) {
    const sa = Math.sin(angle), ca = Math.cos(angle);
    const rx = dx * ca - dy * sa, ry = dx * sa + dy * ca, rz = dz;
    const sd = CFG.curvature > 0.01 ? CFG.sensorDistance + this.getCurvature((px+rx*CFG.sensorDistance)/5, (py+ry*CFG.sensorDistance)/5, (pz+rz*CFG.sensorDistance)/5) * 2 : CFG.sensorDistance;
    return this.getTrail((px + rx * sd) / 5, (py + ry * sd) / 5, (pz + rz * sd) / 5);
  }

  update(scaleIdx) {
    this.step++;
    const sf = Math.max(0.05, Math.min(2, (scaleIdx + 1) / 8));
    const R = CFG.trailRes, R2 = R * R;
    const evap = CFG.evaporation, diff = CFG.diffusion;

    // Trail diffuse
    if (Math.random() < 0.5) {
      for (let i = 0; i < R ** 3; i++) {
        const x = Math.floor(i / R2) % R, y = Math.floor(i / R) % R, z = i % R;
        let sum = this.trail[((x+1)%R)*R2 + y*R + z] + this.trail[((x-1+R)%R)*R2 + y*R + z];
        sum += this.trail[x*R2 + ((y+1)%R)*R + z] + this.trail[x*R2 + ((y-1+R)%R)*R + z];
        sum += this.trail[x*R2 + y*R + (z+1)%R] + this.trail[x*R2 + y*R + (z-1+R)%R];
        this.trail2[i] = this.trail[i] * evap + (sum/6 - this.trail[i]) * diff;
      }
      [this.trail, this.trail2] = [this.trail2, this.trail];
    }

    // Curvature
    if (CFG.curvature > 0.01) {
      for (let i = 0; i < R ** 3; i++) this.curvatureMap[i] *= 0.97;
      const N = CFG.numNodes;
      for (let i = 0; i < N; i++) {
        const cx = this.nodePos[i*3]/5, cy = this.nodePos[i*3+1]/5, cz = this.nodePos[i*3+2]/5;
        const mass = this.nodeMass[i] * CFG.curvature;
        const icx = Math.floor(((cx+100)%1)*R), icy = Math.floor(((cy+100)%1)*R), icz = Math.floor(((cz+100)%1)*R);
        const range = 3;
        for (let dx = -Math.ceil(range); dx <= Math.ceil(range); dx++)
          for (let dy = -Math.ceil(range); dy <= Math.ceil(range); dy++)
            for (let dz = -Math.ceil(range); dz <= Math.ceil(range); dz++) {
              const ix = (icx + dx + 100*R)%R, iy = (icy + dy + 100*R)%R, iz = (icz + dz + 100*R)%R;
              const gx = ix/R - 0.5 + cx, gy = iy/R - 0.5 + cy, gz = iz/R - 0.5 + cz;
              const d2 = gx*gx + gy*gy + gz*gz;
              if (d2 < 4 && d2 > 0.001) this.curvatureMap[(ix*R+iy)*R+iz] += mass / (d2 + 0.1);
            }
      }
    }

    // Agents
    for (const a of this.agents) {
      if (a.tunnelCD > 0) a.tunnelCD--;
      const left = this.sense(a.px, a.py, a.pz, a.dx, a.dy, a.dz, -CFG.sensorAngle);
      const fwd = this.sense(a.px, a.py, a.pz, a.dx, a.dy, a.dz, 0);
      const right = this.sense(a.px, a.py, a.pz, a.dx, a.dy, a.dz, CFG.sensorAngle);
      const noise = (Math.random() - 0.5) * 0.3;
      let ang = noise * 0.2;
      if (fwd <= left || fwd <= right) ang = (left > right ? -1 : 1) * (CFG.rotationAngle + noise);

      // Tunneling
      if (CFG.tunnel > 0.01 && a.tunnelCD === 0 && Math.random() < CFG.tunnel * 0.02) {
        const curveHere = this.getCurvature(a.px/5, a.py/5, a.pz/5);
        if (curveHere > 0.5) {
          const ti = Math.floor(Math.random() * this.agents.length);
          const t = this.agents[ti];
          a.px = t.px + (Math.random() - 0.5) * 2; a.py = t.py + (Math.random() - 0.5) * 2; a.pz = t.pz + (Math.random() - 0.5) * 2;
          a.tunnelCD = 30; continue;
        }
      }

      const ca = Math.cos(ang), sa = Math.sin(ang);
      let ndx = a.dx * ca - a.dy * sa, ndy = a.dx * sa + a.dy * ca, ndz = a.dz + (Math.random() - 0.5) * 0.1;

      // Curvature bending
      if (CFG.curvature > 0.01) {
        const curve = this.getCurvature(a.px/5, a.py/5, a.pz/5);
        if (curve > 0.1) {
          const pullStr = curve * CFG.curvature * 0.1;
          let nnx=0, nny=0, nnz=0, nnw=0;
          for (let i = 0; i < CFG.numNodes; i++) {
            const dx = this.nodePos[i*3] - a.px, dy = this.nodePos[i*3+1] - a.py, dz = this.nodePos[i*3+2] - a.pz;
            const d2 = dx*dx + dy*dy + dz*dz;
            if (d2 < 25 && d2 > 0.01) { const w = this.nodeMass[i] / d2; nnx += dx*w; nny += dy*w; nnz += dz*w; nnw += w; }
          }
          if (nnw > 0) { ndx += nnx/nnw * pullStr; ndy += nny/nnw * pullStr; ndz += nnz/nnw * pullStr; }
        }
      }

      // Dark energy expansion
      if (CFG.darkEnergy > 0.01) {
        ndx += a.px * CFG.darkEnergy * 0.005;
        ndy += a.py * CFG.darkEnergy * 0.005;
        ndz += a.pz * CFG.darkEnergy * 0.005;
      }

      const len = Math.sqrt(ndx*ndx + ndy*ndy + ndz*ndz) || 1;
      a.dx = ndx/len; a.dy = ndy/len; a.dz = ndz/len;
      a.px += a.dx * a.spd * sf; a.py += a.dy * a.spd * sf; a.pz += a.dz * a.spd * sf;
      const bound = 5 * sf;
      if (a.px*a.px + a.py*a.py + a.pz*a.pz > bound*bound) {
        const l = Math.sqrt(a.px*a.px + a.py*a.py + a.pz*a.pz) || 1;
        a.px = -a.px/l * bound * 0.9; a.py = -a.py/l * bound * 0.9; a.pz = -a.pz/l * bound * 0.9;
      }
      this.deposit(a.px/5, a.py/5, a.pz/5, CFG.trailIntensity);
    }

    // Spatial index
    this.spatial.clear();
    const N = CFG.numNodes;
    for (let i = 0; i < N; i++) this.spatial.insert(i, this.nodePos[i*3], this.nodePos[i*3+1], this.nodePos[i*3+2]);

    // Quantum wavefunction
    for (let i = 0; i < N; i++) {
      const h = CFG.quantum;
      let lapR=0, lapI=0; const nearby = this.spatial.query(this.nodePos[i*3], this.nodePos[i*3+1], this.nodePos[i*3+2], 2);
      let cnt = 0;
      for (const j of nearby) {
        if (j === i) continue;
        const dx = this.nodePos[j*3]-this.nodePos[i*3], dy = this.nodePos[j*3+1]-this.nodePos[i*3+1], dz = this.nodePos[j*3+2]-this.nodePos[i*3+2];
        const dist = Math.sqrt(dx*dx+dy*dy+dz*dz) || 0.1;
        lapR += (this.nodeWaveReal[j]-this.nodeWaveReal[i])/dist; lapI += (this.nodeWaveImag[j]-this.nodeWaveImag[i])/dist; cnt++;
      }
      if (cnt > 0) { lapR /= cnt; lapI /= cnt; }
      const V = this.nodeMass[i]*0.5 + this.nodeWeight[i]*0.5 + CFG.higgsField * 0.2;
      const dt = 0.02;
      const dR = (-h*lapI + V*this.nodeWaveImag[i])*dt; const dI = (h*lapR - V*this.nodeWaveReal[i])*dt;
      this.nodeWaveReal[i] += dR; this.nodeWaveImag[i] += dI;
      const prob = this.nodeWaveReal[i]**2 + this.nodeWaveImag[i]**2;
      if (prob > 1) { const s = 1/Math.sqrt(prob); this.nodeWaveReal[i] *= s; this.nodeWaveImag[i] *= s; }
      // Decoherence
      if (CFG.decoherence > 0.001) {
        this.nodeWaveReal[i] *= (1 - CFG.decoherence); this.nodeWaveImag[i] *= (1 - CFG.decoherence);
      }
      // Quantum jitter
      if (h > 0.01) { const j = h * 0.05; this.nodePos[i*3] += (Math.random()-0.5)*j; this.nodePos[i*3+1] += (Math.random()-0.5)*j; this.nodePos[i*3+2] += (Math.random()-0.5)*j; }
    }

    // Entanglement
    if (CFG.entangle > 0.01) {
      for (let i = 0; i < N; i++) for (const j of this.nodeEntangle[i]) {
        if (j <= i) continue;
        const str = CFG.entangle * 0.1;
        const aw = (this.nodeWeight[i]+this.nodeWeight[j])/2;
        this.nodeWeight[i] += (aw-this.nodeWeight[i])*str; this.nodeWeight[j] += (aw-this.nodeWeight[j])*str;
        this.nodePos[i*3] += (this.nodePos[j*3]-this.nodePos[i*3])*str*0.05;
        this.nodePos[i*3+1] += (this.nodePos[j*3+1]-this.nodePos[i*3+1])*str*0.05;
        this.nodePos[i*3+2] += (this.nodePos[j*3+2]-this.nodePos[i*3+2])*str*0.05;
        const asp = (this.nodeSpin[i]+this.nodeSpin[j])/2;
        this.nodeSpin[i] += (asp-this.nodeSpin[i])*str; this.nodeSpin[j] += (asp-this.nodeSpin[j])*str;
      }
    }

    // Gravity
    if (CFG.gravity > 0.01) {
      for (let i = 0; i < N; i++) {
        let gx=0, gy=0, gz=0;
        const nearby = this.spatial.query(this.nodePos[i*3], this.nodePos[i*3+1], this.nodePos[i*3+2], 8);
        for (const j of nearby) {
          if (j === i) continue;
          const dx = this.nodePos[j*3]-this.nodePos[i*3], dy = this.nodePos[j*3+1]-this.nodePos[i*3+1], dz = this.nodePos[j*3+2]-this.nodePos[i*3+2];
          const d2 = dx*dx+dy*dy+dz*dz;
          if (d2 > 0.01 && d2 < 64) { const f = CFG.gravity*this.nodeMass[j]/d2; gx += dx*f; gy += dy*f; gz += dz*f; }
        }
        // Strong force (short-range attraction)
        if (CFG.strongForce > 0.01) {
          for (const j of nearby) {
            if (j === i) continue;
            const dx = this.nodePos[j*3]-this.nodePos[i*3], dy = this.nodePos[j*3+1]-this.nodePos[i*3+1], dz = this.nodePos[j*3+2]-this.nodePos[i*3+2];
            const d2 = dx*dx+dy*dy+dz*dz;
            if (d2 < 4 && d2 > 0.01) { const f = CFG.strongForce*0.3/(d2+0.1); gx += dx*f; gy += dy*f; gz += dz*f; }
          }
        }
        this.nodeVel[i*3] += gx; this.nodeVel[i*3+1] += gy; this.nodeVel[i*3+2] += gz;
      }
    }

    // Dark energy / Inflation expansion
    if (CFG.darkEnergy > 0.01 || CFG.inflation > 0.001) {
      const expFactor = CFG.darkEnergy * 0.002 + CFG.inflation * 0.01;
      for (let i = 0; i < N; i++) {
        this.nodeVel[i*3] += this.nodePos[i*3] * expFactor;
        this.nodeVel[i*3+1] += this.nodePos[i*3+1] * expFactor;
        this.nodeVel[i*3+2] += this.nodePos[i*3+2] * expFactor;
      }
    }

    // Energy shells
    if (CFG.energyShells > 0) {
      for (let i = 0; i < N; i++) {
        const ts = Math.floor(this.nodeWeight[i] * CFG.energyShells);
        const tr = (ts + 1) / (CFG.energyShells + 1) * 6 * sf;
        const cr = Math.sqrt(this.nodePos[i*3]**2 + this.nodePos[i*3+1]**2 + this.nodePos[i*3+2]**2);
        if (cr > 0.01) { const p = (tr-cr)*0.01; this.nodeVel[i*3] += this.nodePos[i*3]/cr*p; this.nodeVel[i*3+1] += this.nodePos[i*3+1]/cr*p; this.nodeVel[i*3+2] += this.nodePos[i*3+2]/cr*p; }
      }
    }

    // Neural dynamics
    const align = CFG.alignStrength, repulse = CFG.repulsionStrength, damp = CFG.damping;
    for (let i = 0; i < N; i++) {
      const px=this.nodePos[i*3], py=this.nodePos[i*3+1], pz=this.nodePos[i*3+2];
      let fx=0, fy=0, fz=0;
      const nearby = this.spatial.query(px, py, pz, 3);
      let cnt=0, ax=0, ay=0, az=0, rx=0, ry=0, rz=0;
      for (const j of nearby) {
        if (j === i) continue;
        const dx=this.nodePos[j*3]-px, dy=this.nodePos[j*3+1]-py, dz=this.nodePos[j*3+2]-pz;
        const d2 = dx*dx+dy*dy+dz*dz;
        if (d2 < 9 && d2 > 0.0001) {
          const w = this.nodeWeight[j]*0.5+0.5; ax += dx*w; ay += dy*w; az += dz*w; cnt++;
          if (d2 < 0.09) { const d = Math.sqrt(d2); const s = repulse/(d+0.01); rx -= dx/d*s; ry -= dy/d*s; rz -= dz/d*s; }
        }
      }
      if (cnt > 0) { fx += ax/cnt*align; fy += ay/cnt*align; fz += az/cnt*align; }
      fx += rx; fy += ry; fz += rz;
      const ti = this.getTrail(px/5, py/5, pz/5);
      fx += (Math.random()-0.5)*ti*0.08; fy += (Math.random()-0.5)*ti*0.08; fz += (Math.random()-0.5)*ti*0.08;

      const aff = i/N, tr = aff*5*sf;
      const cr = Math.sqrt(px*px+py*py+pz*pz);
      if (cr > 0.001) { fx += px/cr*(tr-cr)*0.005; fy += py/cr*(tr-cr)*0.005; fz += pz/cr*(tr-cr)*0.005; }

      // Harmony hooks: gentle orbital revolution + anti-collapse separation keep
      // the ensemble as several orderly clusters instead of one collapsed blob.
      if (CFG.orbital > 0.001 && cr > 0.001) {
        const ux = px/cr, uy = py/cr, uz = pz/cr;
        const tx = -uz, tz = ux;
        const tl = Math.sqrt(tx*tx + tz*tz) || 1;
        fx += tx/tl * CFG.orbital * 0.5;
        fz += tz/tl * CFG.orbital * 0.5;
        fy += (Math.sin(i*0.7) - uy) * CFG.orbital * 0.05;
        fx -= ux * CFG.orbital * 0.06;
        fy -= uy * CFG.orbital * 0.06;
        fz -= uz * CFG.orbital * 0.06;
      }
      if (CFG.separation > 0.001) {
        const crr = cr > 0.001 ? cr : 0.001;
        if (crr < 0.9) {
          const s = (0.9 - crr) * CFG.separation;
          fx -= px/crr*s; fy -= py/crr*s; fz -= pz/crr*s;
        }
      }

      let vx0 = (this.nodeVel[i*3] + fx) * damp;
      let vy0 = (this.nodeVel[i*3+1] + fy) * damp;
      let vz0 = (this.nodeVel[i*3+2] + fz) * damp;
      const vlen = Math.sqrt(vx0*vx0 + vy0*vy0 + vz0*vz0) || 1;
      if (vlen > 0.55){ vx0 *= 0.55/vlen; vy0 *= 0.55/vlen; vz0 *= 0.55/vlen; }
      this.nodeVel[i*3] = vx0; this.nodeVel[i*3+1] = vy0; this.nodeVel[i*3+2] = vz0;
      this.nodePos[i*3] += vx0; this.nodePos[i*3+1] += vy0; this.nodePos[i*3+2] += vz0;
      const maxR = 6*sf;
      const cr2 = Math.sqrt(this.nodePos[i*3]**2+this.nodePos[i*3+1]**2+this.nodePos[i*3+2]**2);
      if (cr2 > maxR) { this.nodePos[i*3]=this.nodePos[i*3]/cr2*maxR*0.95; this.nodePos[i*3+1]=this.nodePos[i*3+1]/cr2*maxR*0.95; this.nodePos[i*3+2]=this.nodePos[i*3+2]/cr2*maxR*0.95; }
      if (CFG.meshShell && cr2 > 0.001) {
        const hR = this.nodeHomeR[i] || cr2;
        const hold = Math.min(1, 0.06 * Math.max(0.0, 1 - CFG.gravity * 0.8));
        this.nodePos[i*3] += (this.nodePos[i*3]/cr2*hR - this.nodePos[i*3]) * hold;
        this.nodePos[i*3+1] += (this.nodePos[i*3+1]/cr2*hR - this.nodePos[i*3+1]) * hold;
        this.nodePos[i*3+2] += (this.nodePos[i*3+2]/cr2*hR - this.nodePos[i*3+2]) * hold;
      }

      let act = 0;
      for (const j of nearby) {
        if (j === i) continue;
        const dx=this.nodePos[j*3]-this.nodePos[i*3], dy=this.nodePos[j*3+1]-this.nodePos[i*3+1], dz=this.nodePos[j*3+2]-this.nodePos[i*3+2];
        if (dx*dx+dy*dy+dz*dz < 9) act += this.nodeWeight[j];
      }
      this.nodeAct[i] = Math.tanh(act * 0.05);
      this.nodeWeight[i] += (this.nodeAct[i]*0.01 - (this.nodeWeight[i]-0.5)*0.005);
      this.nodeWeight[i] = Math.max(0, Math.min(1, this.nodeWeight[i]));
    }

    // Connections
    const connThresh = CFG.connectionThreshold;
    const maxConn = CFG.maxConnections;
    for (let i = 0; i < N; i++) {
      const px=this.nodePos[i*3], py=this.nodePos[i*3+1], pz=this.nodePos[i*3+2];
      const nearby = this.spatial.query(px, py, pz, 2.5);
      const conns = [];
      for (const j of nearby) {
        if (j === i) continue;
        const dx=this.nodePos[j*3]-px, dy=this.nodePos[j*3+1]-py, dz=this.nodePos[j*3+2]-pz;
        const dist = Math.sqrt(dx*dx+dy*dy+dz*dz);
        const trail = this.getTrail((px+this.nodePos[j*3])/10, (py+this.nodePos[j*3+1])/10, (pz+this.nodePos[j*3+2])/10);
        if (dist < connThresh + trail*1.8) conns.push({ t: j, s: trail*this.nodeWeight[i]*this.nodeWeight[j], d: dist });
      }
      conns.sort((a,b)=>b.s-a.s);
      this.connections[i] = conns.slice(0, maxConn);
    }

    // Thermodynamics
    this.totalEnergy = 0; let entSum = 0;
    for (let i = 0; i < N; i++) {
      const ke = (this.nodeVel[i*3]**2+this.nodeVel[i*3+1]**2+this.nodeVel[i*3+2]**2)*this.nodeMass[i]*0.5;
      this.totalEnergy += ke + this.nodeMass[i]*0.5;
      entSum += this.nodeWeight[i] * Math.log(this.nodeWeight[i]+0.001);
    }
    this.entropy = -entSum / N;

    // security system: defenders vs attackers, healing, DDoS waves
    this.secStep();
  }
}



export { SpatialMap, Sim };
